#FROM registry.access.redhat.com/ubi8/ubi:8.0
FROM default-route-openshift-image-registry.apps-crc.testing/openshift/ubi8-openjdk-8:latest
USER 1001
CMD bash -c "while true; do echo test; sleep 5; done"
